### ISSUE TITLE
Quick paint doesn't work

### ISSUE THREAD

**Issue by AstroidexAdam** [aboood40091/Miyamoto#109]
I try to drag tilesets to the quick paint but it does nothing, I tried also to click first on the tilesets and then on quick paint also did nothing.

**Comment by aboood40091** [comment]
1. QuickPaint Tool only accepts objects from the Embedded tab.
2. Just click on the object, then left click on a square in the QuickPaint Tool.

Here is a [video](https://www.youtube.com/watch?v=n-0OXQMB7wY) demonstrating the tool.
