### ISSUE TITLE
Undo/Redo missing

### ISSUE THREAD

**Issue by Flaflo** [aboood40091/Miyamoto#110]
Maybe I am just unable to find it, it appears to me that there is no undo or redo.

**Comment by Anarchy111** [comment]
Yeah, there is no undo, it was just never added.

**Comment by Flaflo** [comment]
> 
> 
> Yeah, there is no undo, it was just never added.

Yes, I noticed that. How can something mandatory like that not be inside an editor?

**Comment by Joey0980** [comment]
> 
> 
> > Yeah, there is no undo, it was just never added.
> 
> Yes, I noticed that. How can something mandatory like that not be inside an editor?

At the time it was probably passed by when the original Reggie was being created, now with the amount of things that would need to be kept track of, it seems as if we won't be getting it any time soon.

**Comment by Flaflo** [comment]
> 
> 
> > > Yeah, there is no undo, it was just never added.
> > 
> > 
> > Yes, I noticed that. How can something mandatory like that not be inside an editor?
> 
> At the time it was probably passed by when the original Reggie was being created, now with the amount of things that would need to be kept track of, it seems as if we won't be getting it any time soon sadly.

Nah, I dont think it is a hard feature to implement. I haven't looked at the code base closely yet, but if it is not spaghetticode it should be relativly easy to implement a tracker that can be back and forth in time.

**Comment by Joey0980** [comment]
> 
> 
> > > > Yeah, there is no undo, it was just never added.
> > > 
> > > 
> > > Yes, I noticed that. How can something mandatory like that not be inside an editor?
> > 
> > 
> > At the time it was probably passed by when the original Reggie was being created, now with the amount of things that would need to be kept track of, it seems as if we won't be getting it any time soon sadly.
> 
> Nah, I dont think it is a hard feature to implement. I haven't looked at the code base closely yet, but if it is not spaghetticode it should be relativly easy to implement a tracker that can go back and forth in time.

You should join the discord https://discord.gg/AvFEHpp we can continue this there if you'd like.

**Comment by aboood40091** [comment]
> > > > Yeah, there is no undo, it was just never added.
> > > 
> > > 
> > > Yes, I noticed that. How can something mandatory like that not be inside an editor?
> > 
> > 
> > At the time it was probably passed by when the original Reggie was being created, now with the amount of things that would need to be kept track of, it seems as if we won't be getting it any time soon sadly.
> 
> Nah, I dont think it is a hard feature to implement. I haven't looked at the code base closely yet, but if it is not spaghetticode it should be relativly easy to implement a tracker that can go back and forth in time.

It is. You are welcome to attempt it though.
In any case, there are no plans to add them to the editor.
