### ISSUE TITLE
Invalid path (NSMBU DX)

### ISSUE THREAD

**Issue by quentinf33** [aboood40091/Miyamoto#112]
Hi!

I extracted Romfs folder with Course folder inside. But when I choose the Course folder in the app, I always have a "Invalid Path!" message. I have my SARC-format levels inside it.

And for precision, I used both v27 and v28 (DX) versions to see if it was a version specific bug.

Thanks for your help.![image](https://user-images.githubusercontent.com/16868850/114747924-a325b000-9d51-11eb-9e64-5e408bf90577.png)

**Comment by aboood40091** [comment]
Hello. For starters, you may want to update to v28.0 (unrelated to the issue, but it's a better version). v29.0 might come out in a few days.
Anyway, make sure the Unit folder is present next to the Course folder.

**Comment by quentinf33** [comment]
Thanks for your fast answer!

Indeed I edited my message.

I tried a few more times and it worked... 

I forgot Unit folder but had an error message after the paths config.

I think it was a bug because I use Windows with Parallels Desktop on my Mac.

Thank you!
