### ISSUE TITLE
Prefabs

### ISSUE THREAD

**Issue by TomatechGames** [aboood40091/Miyamoto#113]
Allow the user to save a pattern of tiles/sprites which can be placed together at the same time, like with clipboards. Prefabs could even get their own pallette tab.

**Comment by aboood40091** [comment]
Already exists. Check the stamps tab.
![image](https://user-images.githubusercontent.com/10743814/117575269-25f01f80-b0f2-11eb-9646-45f511998b52.png)

**Comment by TomatechGames** [comment]
ah, thanks
