### ISSUE TITLE
Problems with saving

### ISSUE THREAD

**Issue by AstroidexAdam** [aboood40091/Miyamoto#62]
I try tio save but it doesn't work in v24.0

**Comment by aboood40091** [comment]
Can you give more details? What platform are you on? Where you using the source code? Where you saving as SARC or SZS? Etc.

**Comment by AstroidexAdam** [comment]
As sarc in the Windows x86 version however i use Windows 10 x64

**Comment by AstroidexAdam** [comment]
and not the source code

**Comment by aboood40091** [comment]
Umm, I think you are missing zlib1.dll.
Download it from here:
https://www.dll-files.com/download/725ab72d5dd462f2edaf1a6c59c8cfb5/zlib1.dll.html?c=NUQ3eHB5aUNJWTg0bEwrVnVFVngzdz09
And then put it in the Tools folder.

**Comment by AstroidexAdam** [comment]
I have still problems with saving :(

**Comment by aboood40091** [comment]
v25 is comming out soon. I hope it fixes your issue.

**Comment by aboood40091** [comment]
Try v26 Beta. If you still happen to get errors, open a new issue with the traceback shown.
