### ISSUE TITLE
'modify selected sprite properties' window

### ISSUE THREAD

**Issue by charlie59876** [aboood40091/Miyamoto#63]
after being afk for a bit whilst not using miyamoto when the window is still open when you click a sprite they stop displaying the 'modify selected sprite properties' window.

**Comment by aboood40091** [comment]
I have noticed this issue before, but I have yet to find out the cause...

**Comment by charlie59876** [comment]
and i've made an objects folder with all the names for the tilesets that could be in the next release: https://drive.google.com/open?id=13UmVDjoTE6XgMuCyVXdPouh-vnI9FFNa
