### ISSUE TITLE
Freezes every time I enter a custom level

### ISSUE THREAD

**Issue by Dylanator6086** [aboood40091/Miyamoto#65]
On the Wii U, everytime I try to load my custom NSMBU levels with loadiine gx2, it freezes. Like when I'm on the world map and try to enter the level, it freezes while its loading the level. I always save my levels as a compressed szs. file.

**Comment by aboood40091** [comment]
You are not giving enough information. Can you send a screenshot of one of those levels?
Also, did you make sure to get data.zip from the releases?

**Comment by Dylanator6086** [comment]
During the loading screen of 1-1, it will introduce the level like 1-1 acorn plains way. While its loading it will freeze and it won't fully load the level.

**Comment by Dylanator6086** [comment]
But I did just download the data zip of Miyamoto v25 but i haven't tested it yet.
