### ISSUE TITLE
Improve saving

### ISSUE THREAD

**Issue by mariomadproductions** [aboood40091/Miyamoto#67]
Some suggestions to improve saving:
* Put the internal level name as a setting, rather than promoting you every save
* Add a save icon back to the toolbar
* Also, if you haven't actually used any extra tiles could you make it so it doesn't recompress everything?
* And maybe you could add an option to include the whole tileset in each level to avoid the compression times? But maybe that'd make the levels too big?

**Comment by aboood40091** [comment]
* Well, I kinda need it to be that way, but I could make it an option in the Miyamoto Preferences.
* Hm... Alright.
* That is what it does though, unless you have the "Always resave the tilesets" option enabled under "Tilesets" in the mainbar.
* I'm not sure what you mean by "the whole tileset".

**Comment by mariomadproductions** [comment]
4. E.g. all the grassland tiles

**Comment by aboood40091** [comment]
That won't be possible.

**Comment by mariomadproductions** [comment]
Could you add an option to save the level data without saving the titleset data? Just in case your computer crashes or something? Then when you want to test the level you can save the whole thing.

**Comment by aboood40091** [comment]
An update on this:
Save has been readded to the toolbar.
I also really don't see the need for saving only the level data as the level is literally useless without its tileset.
In all honesty, I do believe saving to be fast enough as it is. If you still need this feature, open a new issue for it.
