### ISSUE TITLE
Sprite data and rendering for Expanding/Contracting Pipes are wrong

### ISSUE THREAD

**Issue by mariomadproductions** [aboood40091/Miyamoto#70]
The sprite data currently has:
```
<value nybble="11" title="Starting Height" comment="The height when the pipe starts moving."/>
<value nybble="12" title="Ending Height" comment="Goes back up when it reaches this height."/>
```
whereas it should be like this
```
<value nybble="11" title="Ending Height" comment="Goes back up when it reaches this height."/>
<value nybble="12" title="Starting Height" comment="The height when the pipe starts moving."/>
```

The rendering (for the sideways pipes at least) doesn't how it is in-game. The sideways "extended length" rendering is offset by +2 (atl least with some length values). E.g. in-game it will be extended by two, but it will show in the editor as being extended by four.

**Comment by aboood40091** [comment]
Fixed in the [latest commit](https://github.com/aboood40091/Miyamoto/commit/a6af1d2f5edae4793208e550b938ff8d9aaa3d17).
