### ISSUE TITLE
Invalid Game Path

### ISSUE THREAD

**Issue by tytyG** [aboood40091/Miyamoto#84]
What Game Path should I use in the beginning? I'm not completely sure if Windows 7 is compatible, but I followed the steps, and it gives me the Invalid Path! message, no matter what I try.

**Comment by aboood40091** [comment]
You need the course_res_pack folder from a NSMBU dump.

**Comment by tytyG** [comment]
Where is the course_res_pack folder?

**Comment by aboood40091** [comment]
In a NSMBU dump in ``content/Common/``.
