### ISSUE TITLE
Problem with saving :(

### ISSUE THREAD

**Issue by TheRealAsKye** [aboood40091/Miyamoto#87]
I can't save my levels on Miyamoto v24 D:
Really annoying :( Help please, i tried to dl zlib1.dll and drag it in Tools file
Get me an error code.

**Comment by mrbengtsson** [comment]
Please get the latest release before you post about errors. You can get it by running from source. See the readme for an install guide.

**Comment by aboood40091** [comment]
I am surprised you found how to open an issue but couldn't check releases.
