### ISSUE TITLE
Idk how to install v26

### ISSUE THREAD

**Issue by TheRealAsKye** [aboood40091/Miyamoto#88]
There is not miyamoto.exe in the last release, i am dumb ?
Help plz x(

**Comment by mrbengtsson** [comment]
Go to https://github.com/aboood40091/Miyamoto and scroll down to find the installation guide (or open the file readme.md), since you are running from source there is no exe file.

**Comment by Kysonati** [comment]
also make sure to use v27 (latest) and_not_ v26 - that version is broken

**Comment by mrbengtsson** [comment]
Aka: use source

**Comment by Kysonati** [comment]
what if they have v26 source

**Comment by mrbengtsson** [comment]
Okay, I'll be even clearer. Use the **Clone or download** button on https://github.com/aboood40091/Miyamoto to download the **latest source**.

**Comment by TheRealAsKye** [comment]
Sorry to be annoying but, there is no miyamoto.exe in the zip, how can I launch it ?
(Im not english sorry if I spell bad)

**Comment by mrbengtsson** [comment]
You have only downloaded it, right? Then you need to install it, and the installation guide is in the file called readme.md

**Comment by Kysonati** [comment]
or, you could join the official Miyamoto discord server and look at a tutorial there
https://discord.gg/rE43xDG

**Comment by TheRealAsKye** [comment]
Okay im going to read, don't close please I will do it myself if I get it :) Thx !

**Comment by TheRealAsKye** [comment]
Python 3.8.3 is Python 3 ?

**Comment by TheRealAsKye** [comment]
3.8.0 *

**Comment by mrbengtsson** [comment]
Yes

**Comment by TheRealAsKye** [comment]
okay, "Open Command Prompt (or PowerShell) and type the following: "
In cmd or Python cmd ??

**Comment by mrbengtsson** [comment]
Just regular cmd

**Comment by TheRealAsKye** [comment]
Okay im installing Python 3.8 and I check add it to PATH.

**Comment by mrbengtsson** [comment]
Don't forget to install pip as well

**Comment by TheRealAsKye** [comment]
I chech pip too.
Just a question, There is a forum where peoples share nsmbu levels or where people are doing some tutorials for helping ?

**Comment by TheRealAsKye** [comment]
check *

**Comment by mrbengtsson** [comment]
The discord server Kysonati posted a link to earlier is for helping with miyamoto and nsmbu hacking.
Link: https://discord.gg/rE43xDG

**Comment by TheRealAsKye** [comment]
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

its important ?

**Comment by mrbengtsson** [comment]
yeah, do that command to update pip

**Comment by TheRealAsKye** [comment]
okay

**Comment by TheRealAsKye** [comment]
Wow this command py -3 -m pip install Cython
make a big red error text

**Comment by mrbengtsson** [comment]
Try just the cmd: py
And see what it says

**Comment by TheRealAsKye** [comment]
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by mrbengtsson** [comment]
Do: pip

**Comment by TheRealAsKye** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pip' is not defined

**Comment by TheRealAsKye** [comment]
You mean py pip ?

**Comment by mrbengtsson** [comment]
No, only:
pip
And that was what it gave you?

**Comment by TheRealAsKye** [comment]
yes

**Comment by TheRealAsKye** [comment]
wait i try again

**Comment by TheRealAsKye** [comment]
Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to
                              WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup,
                              (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted, even though it does not have valid or any
                              HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the
                              certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output

**Comment by TheRealAsKye** [comment]
Now this, its better

**Comment by mrbengtsson** [comment]
Then run these four commands:
pip install PyQt5
pip install Cython
pip install libyaz0
pip install SarcLib

**Comment by TheRealAsKye** [comment]
PyQt5 has worked, I do it again ?

**Comment by mrbengtsson** [comment]
No, if it already worked just run the next command

**Comment by TheRealAsKye** [comment]
Same error with Cython ://

**Comment by TheRealAsKye** [comment]
ERROR: Command errored out with exit status 1: 'c:\users\megaport\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Megaport\\AppData\\Local\\Temp\\pip-install-iyyyixsa\\Cython\\setup.py'"'"'; __file__='"'"'C:\\Users\\Megaport\\AppData\\Local\\Temp\\pip-install-iyyyixsa\\Cython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Megaport\AppData\Local\Temp\pip-record-an91hqo6\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by TheRealAsKye** [comment]
If it can help u

**Comment by TheRealAsKye** [comment]
Miss click

**Comment by mrbengtsson** [comment]
Run the other two commands and see if the same thing happens

**Comment by TheRealAsKye** [comment]
Done !

**Comment by mrbengtsson** [comment]
You can run miyamoto without Cython but it will be very slow.
Try the command again just to see if the same thing comes up

**Comment by TheRealAsKye** [comment]
There is no way I can install Cython manualy ?

**Comment by TheRealAsKye** [comment]
Same error ://

**Comment by mrbengtsson** [comment]
You'll have to ask aboood40091 for help with cython.
I myself had some problems with it :/

But now everything should work (but very slowly). Try running **run-python.bat**!

**Comment by TheRealAsKye** [comment]
"!" is in the command ?

**Comment by mrbengtsson** [comment]
No, just open the file:
**run-python.bat**

**Comment by TheRealAsKye** [comment]
oh okay sry

**Comment by TheRealAsKye** [comment]
Im in, seem to be fast, not slow ^^

**Comment by TheRealAsKye** [comment]
Thanks a lot !

**Comment by TheRealAsKye** [comment]
I can save, all is good, Bye :)

**Comment by mrbengtsson** [comment]
You also need the data folder if you don't have it already:
https://github.com/aboood40091/Miyamoto/releases/download/v14/data.zip
And also all the tilesets in the game:
https://www.mediafire.com/?uj2b2szy7eytyz3

**Comment by TheRealAsKye** [comment]
I have all of this already ^^
