### ISSUE TITLE
When selecting the Game Path, and changing the name to the specified folder name requires, the error it gives is Invalid path!

### ISSUE THREAD

**Issue by gadielisawesome** [aboood40091/Miyamoto#93]
When launching Miyamoto! v27.0, it launches Game Path (required). So I input the Path with the ... button, but if the correct folder is specified, it gives an **_Invalid path!_** error. So I also tried running it as Administrator, but no luck even when re-downloading to check for corrupted files and folders. Can anybody help me here?

Thanks!

**Comment by mrbengtsson** [comment]
Upload a screenshot of that "correct folder" then we can see what is wrong
