### ISSUE TITLE
Always says 'invalid path' when told to select the 'course_res_pack'.

### ISSUE THREAD

**Issue by EvenMoreFries** [aboood40091/Miyamoto#94]
I downloaded Miyamoto and when told to select the 'course_res_pack' folder, I did. However, even though I have the Objects and Data folders in the 'Miyamoto_Windows_x64_BuildV27.0' folder, it stayed the same. 
![miyamotonotworking](https://user-images.githubusercontent.com/63906340/79635898-a2246780-816b-11ea-9a27-b23b4d8dd706.png)

**Comment by mrbengtsson** [comment]
Upload a screenshot of the course_res_pack folder.

**Comment by EvenMoreFries** [comment]
It's empty.

**Comment by mrbengtsson** [comment]
Yeah... That's not supposed to be empty. That's where all your levels from the game files are supposed to be. You fix that by getting the game files for real.

Or if you want a quick fix the lazy and **_bad way_**: Add a new file in that folder and call it 1-1.szs

**Comment by EvenMoreFries** [comment]
I've done that, and it lets me past that first screen, but tells me to restart the app and doesn't let me do anything.

**Comment by mrbengtsson** [comment]
That's why I called it the bad way. Just get the game files by dumping them from your own copy of nsmbu.

**Comment by AlansGames** [comment]
You just picked the wrong path, believe it or not, there are two course_res_packs. The actual one with all the levels should be in: \content\Common\course_res_pack.
